### PR TITLE
Restructure & refactor

### PR DESCRIPTION
**Pull request by erykpiast**
* library code rewritten to ES6
 * code cleared and refactored a bit
 * example separated from source
 * gulp replaced with NPM scripts
 * added NPM scripts for easy publish (to GitHub so far, not to NPM)
 * dist file included in repository (to make installing directly from GitHub easier)

### CODE REVIEW

**Comment by erykpiast** [comment]
I just want to know if you like those changes and discuss before accepting anything.

**Comment by jiyinyiyong** [comment]
Looks good except for the `dist/` part. I don't want to put compiled code in repo. While it's necessary for npm, I would prefer `lib/x.js` and make it ignored.

**Comment by erykpiast** [comment]
To summarize, I should rename `dist` to `lib` and remove this directory from repository, right?

**Comment by jiyinyiyong** [comment]
Yeah.

**Comment by erykpiast** [comment]
Hey, I've made it.

**Comment by jiyinyiyong** [comment]
Now I'm feeling bad to maintain such heavy ESlint configs. Although it's somehow useful.

**Comment by erykpiast** [comment]
It's better to take some popular one from NPM and just don't care about own habits and preferences ;) But that's not easy thing too!

**Pull request merged**
